### ISSUE TITLE
Server and launcher crash on startup

### ISSUE THREAD

**Issue by Matt0550** [Tictim/Paraglider#18]
Hi, today I downloaded the mod but when starting the launcher or the sever I get this error:
`
---- Minecraft Crash Report ----
// Don't do that.

Time: 15/05/21 12.07
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:429) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tictim.paraglider.ModCfg.init(ModCfg.java:100) ~[paraglider:1.3.1.1] {re:classloading}
-- MOD paraglider --
Details:
	Mod File: Paraglider-1.16.5-1.3.1.1.jar
	Failure message: Paraglider (paraglider) has failed to load correctly
		java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeConfigSpec$Builder.defineListAllowEmpty(Ljava/util/List;Ljava/util/function/Supplier;Ljava/util/function/Predicate;)Lnet/minecraftforge/common/ForgeConfigSpec$ConfigValue;
	Mod Version: 1.3.1.1
	Mod Issue URL: https://github.com/Tictim/Paraglider/issues
	Exception message: java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeConfigSpec$Builder.defineListAllowEmpty(Ljava/util/List;Ljava/util/function/Supplier;Ljava/util/function/Predicate;)Lnet/minecraftforge/common/ForgeConfigSpec$ConfigValue;
Stacktrace:
	at tictim.paraglider.ModCfg.init(ModCfg.java:100) ~[paraglider:1.3.1.1] {re:classloading}
	at tictim.paraglider.ParagliderMod.<init>(ParagliderMod.java:44) ~[paraglider:1.3.1.1] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 245095560 bytes (233 MB) / 746422272 bytes (711 MB) up to 14985461760 bytes (14291 MB)
	CPUs: 8
	JVM Flags: 5 total; -Xmn128M -Xmx14303M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |CREATE_REG|NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |CREATE_REG|NOSIGNATURE
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |CREATE_REG|NOSIGNATURE
		AmbientSounds_v3.1.5_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |CREATE_REG|NOSIGNATURE
		morevanillalib-1.16.4-1.4.0.jar                   |MoreVanillaLib                |morevanillalib                |1.4.0               |CREATE_REG|NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.440-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |CREATE_REG|NOSIGNATURE
		Valhelsia-Structures-Mod-1.16.4.jar               |Valhelsia Structures          |valhelsia_structures          |16.0.5              |CREATE_REG|NOSIGNATURE
		ironfurnaces-1.16.5-2.6.8.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.8               |CREATE_REG|NOSIGNATURE
		SimpleCoreLib-1.16.4-2.0.4.3.jar                  |SimpleCoreLib                 |simplecorelib                 |1.16.4-2.0.4.3      |CREATE_REG|NOSIGNATURE
		CreativeCore_v2.1.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|NOSIGNATURE
		morevanillatools-1.16.4-2.2.0.jar                 |MoreVanillaTools              |morevanillatools              |2.2.0               |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.74.jar                           |Just Enough Items             |jei                           |7.6.1.74            |CREATE_REG|NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |CREATE_REG|NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |CREATE_REG|NOSIGNATURE
		randomenchants-4.0.4.jar                          |Random Enchants               |randomenchants                |4.0.4               |CREATE_REG|NOSIGNATURE
		Xaeros_Minimap_21.8.1_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.8.1              |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		TravelersBackpack-1.16.4-5.3.8.jar                |Traveler's Backpack           |travelersbackpack             |5.3.8               |CREATE_REG|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |CREATE_REG|NOSIGNATURE
		quickteleports-1.16.2-1.1.2.jar                   |QuickTeleports                |quickteleports                |1.1.2               |CREATE_REG|NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |CREATE_REG|NOSIGNATURE
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |CREATE_REG|e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |CREATE_REG|NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |CREATE_REG|NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |CREATE_REG|d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		morevanillaarmor-1.16.4-1.2.1.jar                 |MoreVanillaArmor              |morevanillaarmor              |1.16.4-1.2.1        |CREATE_REG|NOSIGNATURE
		mcw-doors-1.0.2-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.2               |CREATE_REG|NOSIGNATURE
		furniture-7.0.0-pre19-1.16.3.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |CREATE_REG|NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |CREATE_REG|NOSIGNATURE
		Hwyla-Mod-1.16.3.jar                              |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|NOSIGNATURE
		FpsReducer-mc1.16.5-1.19.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.5-1.19       |CREATE_REG|NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |CREATE_REG|8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Paraglider-1.16.5-1.3.1.1.jar                     |Paraglider                    |paraglider                    |1.3.1.1             |ERROR     |NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-305.jar                                |Quark                         |quark                         |r2.4-305            |CREATE_REG|NOSIGNATURE
		tl_skin_cape_forge_1.16.4-1.16.jar                |TLSkinCape                    |tlskincape                    |1.6                 |CREATE_REG|19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		Upgraded+Netherite+1.16.5+-+1.9.2.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |CREATE_REG|NOSIGNATURE
		SimpleOres2-1.16.4-2.4.3.10.jar                   |Simple Ores                   |simpleores                    |1.16.4-2.4.3.10     |CREATE_REG|NOSIGNATURE
	Crash Report UUID: c7386a5a-048b-4632-9fc8-215b621532b2
	OptiFine Version: OptiFine_1.16.4_HD_U_G7
	OptiFine Build: 20210221-012854
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.283 Lite.zip
	OpenGlVersion: 4.6.0 NVIDIA 466.27
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
`

**Comment by Tictim** [comment]
Update Forge
